trying to fix rhacs operator installation

diff --git a/components/apps/rhacs-full-stack/templates/jobs/check_if_operator_is_ready.yaml b/components/apps/rhacs-full-stack/templates/jobs/check_if_operator_is_ready.yaml
--- a/components/apps/rhacs-full-stack/templates/jobs/check_if_operator_is_ready.yaml
+++ b/components/apps/rhacs-full-stack/templates/jobs/check_if_operator_is_ready.yaml
@@ -16,34 +16,53 @@ spec:
             - /bin/bash
             - -c
             - |
-              #!/usr/bin/env bash
+             #!/usr/bin/env bash
               # Wait for central to be ready
               attempt_counter=0
               max_attempts=20
+              sleep_timer=20
+              crd_check_time=5
+              status=0
 
               echo "Waiting for operator to be available..."
 
               # we assume that the operator is ready, once the CRD Central is available.
               # when this is the case ArgoCD can continue
-              until $(oc get crd/centrals.platform.stackrox.io &>/dev/null); do
+              #until $(oc get crd/centrals.platform.stackrox.io &>/dev/null); do
                   if [ ${attempt_counter} -eq ${max_attempts} ];then
                     echo "Max attempts reached. I give up"
                     exit 1
                   fi
                   attempt_counter=$(($attempt_counter+1))
                   echo "Made attempt $attempt_counter of $max_attempts, waiting..."
-                  sleep 5
-              done
+                  sleep $crd_check_time
+              #done
+
+              echo "Custom Resources are available, checking Deployment"
 
               # turned out it takes even more time until operator is ready, so lets check the deployment
               deployments=(rhacs-operator-controller-manager)
               for i in "${deployments[@]}";
               do
                 printf "\nWaiting for deployment $i\n";
+                oc get $i -n rhacs-operator
+                depl_status=$?
+                if [ $depl_status -eq 1 ]; then
+                    echo "Deployment not yet found... Give Operator $sleep_timer seconds to create the Deployment"
+                    sleep $sleep_timer
+                fi
                 oc rollout status deployment $i -n rhacs-operator
+                status=$?
               done
 
-              echo "Operator seems to be ready"
+              echo $status
+
+              if [ $status -eq 0 ]; then
+                  echo "Operator seems to be ready"
+              else
+                  echo "ERROR: Operator is not ready"
+                  exit 1
+              fi
           name: init-quay
       dnsPolicy: ClusterFirst
       restartPolicy: Never
