testing linting action

diff --git a/.github/workflows/linting.yml b/.github/workflows/linting.yml
--- a/.github/workflows/linting.yml
+++ b/.github/workflows/linting.yml
@@ -2,9 +2,9 @@ name: Linting
 
 on: 
   workflow_dispatch:
-#  push:
-#    branches: 
-#      - main
+  push:
+    branches: 
+      - main
   pull_request:
     paths-ignore:
       - '.github/**'
@@ -19,11 +19,69 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Run chart-testing (list-changed)
+      - name: Run helm lint on found Charts
         id: list-changed
         run: |
-          ls -la 
-          yamllint -h 
-          helm version 
-          kube-score
-          kube-linter
+          #!/usr/bin/env bash
+
+          for charts in $(find . -name 'Chart.yaml'); do
+            helm_dir=$(dirname "${charts}")
+            helm lint --strict "${helm_dir}"
+          done
+
+      - name: Run yamllint on all values-files
+        id: list-changed
+        run: |
+          #!/usr/bin/env bash
+
+          for values_files in $(find . -type f -name '*values.yaml'); do
+            yamllint -c .yamllint.yaml ${values_files}; let var=var+$?
+          done
+
+          (exit $var)
+
+      - name: Run kube-score
+        id: list-changed
+        run: |
+          #!/usr/bin/env bash
+
+          KUBESCORE_IGNORE_TESTS="${KUBESCORE_IGNORE_TESTS:-container-image-pull-policy,pod-networkpolicy}"
+          RC=0
+
+          for charts in $(find ~+ -name 'Chart.yaml'); do
+
+            # get helm charts
+            helm_dir=$(dirname "${charts}")
+            helm_name=$(basename $helm_dir)
+
+            # create tmp output for helm charts and do a "helm template"
+            helm_output_dir=$(mktemp -d 2>/dev/null)
+            helm template $helm_dir --output-dir $helm_output_dir/$helm_name
+            [ ! -d "$helm_output_dir/$helm_name" ] && echo "Unable to resolve helm template" && exit 1
+
+            # for all files in the output folder of the helm charts, do a kube-score
+            find $helm_output_dir -name '*' -type f -exec cat {} \; | kube-score score --ignore-test ${KUBESCORE_IGNORE_TESTS} -
+            if [ $? -gt 0 ]; then
+              RC=1
+            fi
+
+            rm -rf $helm_output_dir
+          done
+
+          (exit $RC)
+
+      - name: Run kube-linter
+        id: list-changed
+        run: |
+          #!/usr/bin/env bash
+
+          RC=0
+          for charts in $(find . -name 'Chart.yaml'); do
+            helm_dir=$(dirname "${charts}")
+
+            kube-linter lint ${helm_dir} --config ".kube-linter.yaml"
+            if [ $? -gt 0 ]; then
+              RC=1
+            fi
+          done
+          (exit $RC)
